export const DESCRIPTION_NOT_USED_PLACEHOLDER = '';
export const NAME_INPUT_CHAR_LIMIT = 120;
export const DESCRIPTION_INPUT_CHAR_LIMIT = 500;
export const PAGE_SIZE_TO_GET_ALL = 999;
export const INPUT_DEBOUNCE_MS = 500;
