pipeline:
  build:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      tags: latest
    secrets: [ docker_username, docker_password ]
when:
  branch: master
  event: push
