pipeline:
  install:
    image: danlynn/ember-cli:4.4.0-node_16.15
    commands:
      - npm ci
  lint:
    image: danlynn/ember-cli:4.4.0-node_16.15
    commands:
      - npm run lint
  tests:
    image: danlynn/ember-cli:4.4.0-node_16.15
    commands:
      - npm run test:ember
when:
  event:
    - pull_request
