pipeline:
  install:
    image: danlynn/ember-cli:3.28.2-node_14.18
    commands:
    - npm install
    when:
      event:
        - pull_request
  lint:
    image: danlynn/ember-cli:3.28.2-node_14.18
    commands:
    - npm run lint
    when:
      event:
        - pull_request
  run-tests:
    image: danlynn/ember-cli:3.28.2-node_14.18
    commands:
    - npm run test:ember
    when:
      event:
        - pull_request
